### ISSUE TITLE
Dynamic content/JavaScript

### ISSUE THREAD

**Issue by winkerVSbecks** [c8r/support#1]
First of all this is really 🆒 !

Correct me if I'm wrong… the general idea is that you write markdown files for content and everything else around it is React components that we can configure through the UI or `compositor.json` file. 

Is it possible to have dynamic content? For example I threw in some `divs`, `style` tags and loading some JS using `script` tags. All of that is stripped out. How can I include those? Or is that not really something I should be doing?

**Comment by jxnblk** [comment]
Thanks!

For now, the MVP uses markdown from a repo's README.md, but we plan to support a lot more in the future. Unfortunately, due to XSS attacks, we can't safely allow certain HTML tags (e.g. script) in the markdown file to be used in your site. We hope to have more flexible options soon, but as you pointed out, the `compositor.json` file is the source of truth for configuring the site.
